### Dataset - https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

In [1]:
# doing necessary imports

import numpy as np
print(np.__version__)

1.26.2


In [2]:
# read and save the original dataset

original_ds =np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', 
                 dtype='object', delimiter=',', usecols=())
original_ds

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

### 1. Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)

In [3]:
# make a copy of original dataset and cut off the last column
ds_ = np.array(original_ds[:, :-1])

# other way - delete the last column
ds = np.delete(original_ds, -1, axis=1)

# ensure both methods make the same result
print(np.array_equal(ds_, ds))

# convert ds to 'float32' type
ds = ds.astype('float32')
ds

True


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

### 2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)

In [4]:
# ensure we have a 2d array and view other characteristics 
print(ds.ndim, ds.shape, ds.dtype, ds.itemsize, ds.size, sep='\n') 

2
(150, 4)
float32
4
600


### 3. Порахувати mean, median, standard deviation для 1-ї колонки

In [5]:
# make a view of the first column 
first_col = ds[:, 0]

# calc and print necessary funcs
print(
    np.mean(first_col),
    np.median(first_col),
    np.std(first_col),
    sep='\n'
)

5.8433332
5.8
0.8253013


### 4. Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

In [6]:
np.random.seed(42)

# generate 20 unique values from all elements indexes in ds 
random_20_indexes = np.random.choice(ds.size, size=20, replace=False)

# make a flat view of ds, so we can apply an index array we've got above 
ds_flat_view = ds.ravel()

# set nan to elements in ds applying index array
ds_flat_view[random_20_indexes] = np.nan

print(random_20_indexes)
print(ds)

[110 419 565  77 181 284  10 469  78 349  55 118 109 588 369 234  30 212
 184  86]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 nan 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 nan 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 nan]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 nan nan 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 nan 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 nan nan 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 nan 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 nan 1.4 0.3]
 [nan 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3

### 5. Знайти позиції вставлених значень np.nan в 1-й колонці

In [7]:
# the first way - get 1d index only inside 1st column
first_col = ds[:, 0]
first_col_nan_indexes = np.nonzero(np.isnan(first_col))

print(first_col_nan_indexes)

# # the second way - get 2d indexes like in ds
# first_col_nan_mask = np.isnan(first_col)
# first_col_nan_indexes = [index for index,value in np.ndenumerate(first_col_nan_mask) if value]
# 
# print(first_col_nan_indexes)

(array([ 46,  53,  71, 147]),)


### 6. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

In [8]:
# prepare mask
first_col_mask = ds[:, 0] < 5
third_col_mask = ds[:, 2] > 1.5
mask = first_col_mask & third_col_mask

# apply mask to ds
filtered_ds = ds[mask]
print(filtered_ds)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### 7. Замінити всі значення np.nan на 0

In [9]:
# prepare mask
nan_mask = np.isnan(ds)

# apply mask
ds = np.where(nan_mask, 0, ds)
print(ds)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 0.  0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0. ]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 0.  0.  0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 0.  0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 0.  0.  0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 0.  1.4 0.3]
 [0.  3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### 8. Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю 

In [10]:
values, counts = np.unique(ds, return_counts=True)
print(values, counts, sep='\n')

[0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9]
[20  5 28  7  7  1  1  8  4  7 19 20 22 10  6 12  7  7  6  5 11  6 11  4
  9 14 10 26 11 13  8 12  7  4  4  5  5  6  4  5  3  8  9  6  7  9 11 14
 16  6  3  8  9 12 11 10  5  8  8  4 10  8  4  3 10  3  5  1  1  3  1  1
  1  4  1]


### 9. Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

In [11]:
upper_ds, lower_ds = np.vsplit(ds, 2)
print(upper_ds, lower_ds, sep='\n')

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 0.  0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0. ]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 0.  0.  0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 0.  0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 0.  0.  0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 0.  1.4 0.3]
 [0.  3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### 10. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

In [12]:
# prepare sorting masks
upper_ds_sort_index = upper_ds[:, 0].argsort()
lower_ds_sort_index = lower_ds[:, 0].argsort()[::-1]  # [::-1] inverts order 

# doing sort by applying sorting masks
upper_ds = upper_ds[upper_ds_sort_index]
lower_ds = lower_ds[lower_ds_sort_index]
print(upper_ds, lower_ds, sep='\n')

[[0.  3.8 1.6 0.2]
 [0.  2.3 4.  1.3]
 [0.  2.8 4.  1.3]
 [4.3 3.  1.1 0. ]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.7 3.2 0.  0.2]
 [4.8 0.  1.4 0.3]
 [4.8 3.4 1.9 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.5 1.6 0.6]
 [5.  3.3 1.4 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.5 1.3 0.3]
 [5.  3.4 0.  0.2]
 [5.  3.6 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 0.  0.  0.3]
 [5.1 3.3 1.7 0.5]
 [5.1 3.7 0.  0.4]
 [5.1 3.5 1.4 0.3]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 0.  0.  0.2]
 [5.2 2.7 3.9 1.4]
 [5.3 3.7 1.5 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.5 3.5 1.3 0.2]
 [5.5 4.2 1.4 0.2]
 [5.6 2.9 3.

### 11. Зібрати обидва массиви в одне ціле

In [13]:
ds_new = np.vstack([upper_ds, lower_ds])
print(ds_new)

[[0.  3.8 1.6 0.2]
 [0.  2.3 4.  1.3]
 [0.  2.8 4.  1.3]
 [4.3 3.  1.1 0. ]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.7 3.2 0.  0.2]
 [4.8 0.  1.4 0.3]
 [4.8 3.4 1.9 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.5 1.6 0.6]
 [5.  3.3 1.4 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.5 1.3 0.3]
 [5.  3.4 0.  0.2]
 [5.  3.6 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 0.  0.  0.3]
 [5.1 3.3 1.7 0.5]
 [5.1 3.7 0.  0.4]
 [5.1 3.5 1.4 0.3]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 0.  0.  0.2]
 [5.2 2.7 3.9 1.4]
 [5.3 3.7 1.5 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.5 3.5 1.3 0.2]
 [5.5 4.2 1.4 0.2]
 [5.6 2.9 3.

### 12. Знайти найбільш часто повторюване значення в массиві

In [14]:
values, counts = np.unique(ds_new, return_counts=True)
print(values, counts, sep='\n')

most_frequently_value = values[counts == counts.max()][0]
print(most_frequently_value)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9]
[20  5 28  7  7  1  1  8  4  7 19 20 22 10  6 12  7  7  6  5 11  6 11  4
  9 14 10 26 11 13  8 12  7  4  4  5  5  6  4  5  3  8  9  6  7  9 11 14
 16  6  3  8  9 12 11 10  5  8  8  4 10  8  4  3 10  3  5  1  1  3  1  1
  1  4  1]
0.2


### 13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

In [15]:
def my_func(col: np.ndarray) -> np.ndarray:
    average = col.mean()
    col = np.where(col < average, col * 2, col / 4)
    return col

### 14. Застосувати отриману функцію до 3-ї колонки

In [16]:
# the third column is ds_new[:,2]
ds_new[:,2] = my_func(ds_new[:,2])
print(ds_new)

[[0.    3.8   3.2   0.2  ]
 [0.    2.3   1.    1.3  ]
 [0.    2.8   1.    1.3  ]
 [4.3   3.    2.2   0.   ]
 [4.4   3.    2.6   0.2  ]
 [4.4   3.2   2.6   0.2  ]
 [4.4   2.9   2.8   0.2  ]
 [4.5   2.3   2.6   0.3  ]
 [4.6   3.4   2.8   0.3  ]
 [4.6   3.1   3.    0.2  ]
 [4.6   3.6   2.    0.2  ]
 [4.6   3.2   2.8   0.2  ]
 [4.7   3.2   0.    0.2  ]
 [4.7   3.2   0.    0.2  ]
 [4.8   0.    2.8   0.3  ]
 [4.8   3.4   3.8   0.2  ]
 [4.8   3.4   3.2   0.2  ]
 [4.8   3.    2.8   0.1  ]
 [4.8   3.1   3.2   0.2  ]
 [4.9   3.1   3.    0.1  ]
 [4.9   2.4   6.6   1.   ]
 [4.9   3.1   3.    0.1  ]
 [4.9   3.    2.8   0.2  ]
 [4.9   3.1   3.    0.1  ]
 [5.    3.5   3.2   0.6  ]
 [5.    3.3   2.8   0.2  ]
 [5.    2.    7.    1.   ]
 [5.    3.    3.2   0.2  ]
 [5.    3.4   3.2   0.4  ]
 [5.    3.5   2.6   0.3  ]
 [5.    3.4   0.    0.2  ]
 [5.    3.6   2.8   0.2  ]
 [5.    3.2   2.4   0.2  ]
 [5.1   3.8   3.8   0.4  ]
 [5.1   3.4   3.    0.2  ]
 [5.1   3.5   2.8   0.2  ]
 [5.1   0.    0.    0.3  ]
 